version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automated"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automated"

  - package-ecosystem: "gomod"
    directory: "/tools/sync"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automated"
