name: Secret Scan
on:
  pull_request:
  push:
    branches: [main]

jobs:
  trivy-scan:
    uses: y-maeda1116/security-base/.github/workflows/reusable-secret-scan.yml@main
    with:
      scan-tool: "trivy"

  gitleaks-scan:
    uses: y-maeda1116/security-base/.github/workflows/reusable-secret-scan.yml@main
    with:
      scan-tool: "gitleaks"
